##data preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
campus = pd.read_csv('/content/Placement_Data_Full_Class.csv')

In [3]:
campus

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0        1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1        2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2        3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3        4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4        5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0
..     ...    ...    ...      ...  ...             ...    ...         ...       ...
210    211      M  80.60   Others  ...         Mkt&Fin  74.49      Placed  400000.0
211    212      M  58.00   Others  ...         Mkt&Fin  53.62      Placed  275000.0
212    213      M  67.00   Others  ...         Mkt&Fin  69.72      Placed  295000.0
213    214      F  74.00   Others  ...          Mkt&HR  60.23      Placed  204000.0
214    215      M  62.00  Central  ...          Mkt&HR  60.22  Not Placed       NaN

[215 rows x 15 columns]

In [4]:
print(campus['status'].unique())

['Placed' 'Not Placed']


In [5]:
print(campus['specialisation'].unique())

['Mkt&HR' 'Mkt&Fin']


In [6]:
print(campus['gender'].unique())

['M' 'F']


In [7]:
campus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    object 
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object 
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object 
 6   hsc_s           215 non-null    object 
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object 
 9   workex          215 non-null    object 
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object 
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object 
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


In [8]:
campus.describe()

sl_no       ssc_p  ...       mba_p         salary
count  215.000000  215.000000  ...  215.000000     148.000000
mean   108.000000   67.303395  ...   62.278186  288655.405405
std     62.209324   10.827205  ...    5.833385   93457.452420
min      1.000000   40.890000  ...   51.210000  200000.000000
25%     54.500000   60.600000  ...   57.945000  240000.000000
50%    108.000000   67.000000  ...   62.000000  265000.000000
75%    161.500000   75.700000  ...   66.255000  300000.000000
max    215.000000   89.400000  ...   77.890000  940000.000000

[8 rows x 7 columns]

##seperate features and target


In [9]:
x = campus.drop(['status','salary'],axis=1)
y = campus.iloc[:,-2]

In [10]:
x

sl_no gender  ssc_p    ssc_b  ...  workex etest_p specialisation  mba_p
0        1      M  67.00   Others  ...      No    55.0         Mkt&HR  58.80
1        2      M  79.33  Central  ...     Yes    86.5        Mkt&Fin  66.28
2        3      M  65.00  Central  ...      No    75.0        Mkt&Fin  57.80
3        4      M  56.00  Central  ...      No    66.0         Mkt&HR  59.43
4        5      M  85.80  Central  ...      No    96.8        Mkt&Fin  55.50
..     ...    ...    ...      ...  ...     ...     ...            ...    ...
210    211      M  80.60   Others  ...      No    91.0        Mkt&Fin  74.49
211    212      M  58.00   Others  ...      No    74.0        Mkt&Fin  53.62
212    213      M  67.00   Others  ...     Yes    59.0        Mkt&Fin  69.72
213    214      F  74.00   Others  ...      No    70.0         Mkt&HR  60.23
214    215      M  62.00  Central  ...      No    89.0         Mkt&HR  60.22

[215 rows x 13 columns]

In [11]:
y

0          Placed
1          Placed
2          Placed
3      Not Placed
4          Placed
          ...    
210        Placed
211        Placed
212        Placed
213        Placed
214    Not Placed
Name: status, Length: 215, dtype: object

In [12]:
x = x.to_numpy()
print(x)

[[1 'M' 67.0 ... 55.0 'Mkt&HR' 58.8]
 [2 'M' 79.33 ... 86.5 'Mkt&Fin' 66.28]
 [3 'M' 65.0 ... 75.0 'Mkt&Fin' 57.8]
 ...
 [213 'M' 67.0 ... 59.0 'Mkt&Fin' 69.72]
 [214 'F' 74.0 ... 70.0 'Mkt&HR' 60.23]
 [215 'M' 62.0 ... 89.0 'Mkt&HR' 60.22]]


In [13]:
y = y.to_numpy()
print(y)

['Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Not Placed'
 'Not Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed'
 'Not Placed' 'Placed' 'Not Placed' 'Placed' 'Placed' 'Not Placed'
 'Not Placed' 'Placed' 'Placed' 'Placed' 'Placed' 'Placed' 'Placed'
 'Not Placed' 'Placed' 'Placed' 'Placed' 'Not Placed' 'Placed'
 'Not Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Not Placed'
 'Placed' 'Placed' 'Placed' 'Placed' 'Not Placed' 'Not Placed' 'Placed'
 'Placed' 'Not Placed' 'Not Placed' 'Placed' 'Placed' 'Not Placed'
 'Placed' 'Not Placed' 'Not Placed' 'Placed' 'Placed' 'Placed' 'Placed'
 'Placed' 'Placed' 'Placed' 'Placed' 'Placed' 'Placed' 'Not Placed'
 'Placed' 'Not Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed'
 'Placed' 'Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed'
 'Placed' 'Not Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed'
 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed' 'Placed' 'Not Placed'
 'Placed' 'Not Placed' 'Placed' 'Placed' 'Plac

##OneHotEncoder

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [15]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder='passthrough')

In [16]:
x = np.array(ct.fit_transform(x))

In [17]:
x

array([[0.0, 1.0, 1, ..., 55.0, 'Mkt&HR', 58.8],
       [0.0, 1.0, 2, ..., 86.5, 'Mkt&Fin', 66.28],
       [0.0, 1.0, 3, ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       [0.0, 1.0, 213, ..., 59.0, 'Mkt&Fin', 69.72],
       [1.0, 0.0, 214, ..., 70.0, 'Mkt&HR', 60.23],
       [0.0, 1.0, 215, ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [18]:
temp= pd.DataFrame(data=x)

In [19]:
temp

0  1    2      3        4   ...         9    10    11       12     13
0    0  1    1     67   Others  ...   Sci&Tech   No    55   Mkt&HR   58.8
1    0  1    2  79.33  Central  ...   Sci&Tech  Yes  86.5  Mkt&Fin  66.28
2    0  1    3     65  Central  ...  Comm&Mgmt   No    75  Mkt&Fin   57.8
3    0  1    4     56  Central  ...   Sci&Tech   No    66   Mkt&HR  59.43
4    0  1    5   85.8  Central  ...  Comm&Mgmt   No  96.8  Mkt&Fin   55.5
..  .. ..  ...    ...      ...  ...        ...  ...   ...      ...    ...
210  0  1  211   80.6   Others  ...  Comm&Mgmt   No    91  Mkt&Fin  74.49
211  0  1  212     58   Others  ...   Sci&Tech   No    74  Mkt&Fin  53.62
212  0  1  213     67   Others  ...  Comm&Mgmt  Yes    59  Mkt&Fin  69.72
213  1  0  214     74   Others  ...  Comm&Mgmt   No    70   Mkt&HR  60.23
214  0  1  215     62  Central  ...  Comm&Mgmt   No    89   Mkt&HR  60.22

[215 rows x 14 columns]

In [20]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [4])], remainder='passthrough')

In [21]:
x = np.array(ct.fit_transform(x))

In [22]:
x

array([[0.0, 1.0, 0.0, ..., 55.0, 'Mkt&HR', 58.8],
       [1.0, 0.0, 0.0, ..., 86.5, 'Mkt&Fin', 66.28],
       [1.0, 0.0, 0.0, ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       [0.0, 1.0, 0.0, ..., 59.0, 'Mkt&Fin', 69.72],
       [0.0, 1.0, 1.0, ..., 70.0, 'Mkt&HR', 60.23],
       [1.0, 0.0, 0.0, ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [23]:
temp= pd.DataFrame(data=x)

In [24]:
temp

0  1  2  3    4      5   ...     9          10   11    12       13     14
0    0  1  0  1    1     67  ...     58   Sci&Tech   No    55   Mkt&HR   58.8
1    1  0  0  1    2  79.33  ...  77.48   Sci&Tech  Yes  86.5  Mkt&Fin  66.28
2    1  0  0  1    3     65  ...     64  Comm&Mgmt   No    75  Mkt&Fin   57.8
3    1  0  0  1    4     56  ...     52   Sci&Tech   No    66   Mkt&HR  59.43
4    1  0  0  1    5   85.8  ...   73.3  Comm&Mgmt   No  96.8  Mkt&Fin   55.5
..  .. .. .. ..  ...    ...  ...    ...        ...  ...   ...      ...    ...
210  0  1  0  1  211   80.6  ...   77.6  Comm&Mgmt   No    91  Mkt&Fin  74.49
211  0  1  0  1  212     58  ...     72   Sci&Tech   No    74  Mkt&Fin  53.62
212  0  1  0  1  213     67  ...     73  Comm&Mgmt  Yes    59  Mkt&Fin  69.72
213  0  1  1  0  214     74  ...     58  Comm&Mgmt   No    70   Mkt&HR  60.23
214  1  0  0  1  215     62  ...     53  Comm&Mgmt   No    89   Mkt&HR  60.22

[215 rows x 15 columns]

In [25]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [7])], remainder='passthrough')

In [26]:
x = np.array(ct.fit_transform(x))

In [27]:
x

array([[0.0, 1.0, 0.0, ..., 55.0, 'Mkt&HR', 58.8],
       [0.0, 1.0, 1.0, ..., 86.5, 'Mkt&Fin', 66.28],
       [1.0, 0.0, 1.0, ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       [0.0, 1.0, 0.0, ..., 59.0, 'Mkt&Fin', 69.72],
       [0.0, 1.0, 0.0, ..., 70.0, 'Mkt&HR', 60.23],
       [0.0, 1.0, 1.0, ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [28]:
temp= pd.DataFrame(data=x)

In [29]:
temp

0  1  2  3  4  5   ...     10         11   12    13       14     15
0    0  1  0  1  0  1  ...     58   Sci&Tech   No    55   Mkt&HR   58.8
1    0  1  1  0  0  1  ...  77.48   Sci&Tech  Yes  86.5  Mkt&Fin  66.28
2    1  0  1  0  0  1  ...     64  Comm&Mgmt   No    75  Mkt&Fin   57.8
3    1  0  1  0  0  1  ...     52   Sci&Tech   No    66   Mkt&HR  59.43
4    1  0  1  0  0  1  ...   73.3  Comm&Mgmt   No  96.8  Mkt&Fin   55.5
..  .. .. .. .. .. ..  ...    ...        ...  ...   ...      ...    ...
210  0  1  0  1  0  1  ...   77.6  Comm&Mgmt   No    91  Mkt&Fin  74.49
211  0  1  0  1  0  1  ...     72   Sci&Tech   No    74  Mkt&Fin  53.62
212  0  1  0  1  0  1  ...     73  Comm&Mgmt  Yes    59  Mkt&Fin  69.72
213  0  1  0  1  1  0  ...     58  Comm&Mgmt   No    70   Mkt&HR  60.23
214  0  1  1  0  0  1  ...     53  Comm&Mgmt   No    89   Mkt&HR  60.22

[215 rows x 16 columns]

In [30]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [9])], remainder='passthrough')

In [31]:
x = np.array(ct.fit_transform(x))

In [32]:
x

array([[0.0, 1.0, 0.0, ..., 55.0, 'Mkt&HR', 58.8],
       [0.0, 0.0, 1.0, ..., 86.5, 'Mkt&Fin', 66.28],
       [1.0, 0.0, 0.0, ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       [0.0, 1.0, 0.0, ..., 59.0, 'Mkt&Fin', 69.72],
       [0.0, 1.0, 0.0, ..., 70.0, 'Mkt&HR', 60.23],
       [0.0, 0.0, 1.0, ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [33]:
temp= pd.DataFrame(data=x)

In [34]:
temp

0  1  2  3  4  5  6   ...     11     12         13   14    15       16     17
0    0  1  0  0  1  0  1  ...     91     58   Sci&Tech   No    55   Mkt&HR   58.8
1    0  0  1  0  1  1  0  ...  78.33  77.48   Sci&Tech  Yes  86.5  Mkt&Fin  66.28
2    1  0  0  1  0  1  0  ...     68     64  Comm&Mgmt   No    75  Mkt&Fin   57.8
3    0  0  1  1  0  1  0  ...     52     52   Sci&Tech   No    66   Mkt&HR  59.43
4    0  1  0  1  0  1  0  ...   73.6   73.3  Comm&Mgmt   No  96.8  Mkt&Fin   55.5
..  .. .. .. .. .. .. ..  ...    ...    ...        ...  ...   ...      ...    ...
210  0  1  0  0  1  0  1  ...     82   77.6  Comm&Mgmt   No    91  Mkt&Fin  74.49
211  0  0  1  0  1  0  1  ...     60     72   Sci&Tech   No    74  Mkt&Fin  53.62
212  0  1  0  0  1  0  1  ...     67     73  Comm&Mgmt  Yes    59  Mkt&Fin  69.72
213  0  1  0  0  1  0  1  ...     66     58  Comm&Mgmt   No    70   Mkt&HR  60.23
214  0  0  1  0  1  1  0  ...     58     53  Comm&Mgmt   No    89   Mkt&HR  60.22

[215 rows x 18 columns]

In [35]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [13])], remainder='passthrough')

In [36]:
x = np.array(ct.fit_transform(x))

In [37]:
x

array([[0.0, 0.0, 1.0, ..., 55.0, 'Mkt&HR', 58.8],
       [0.0, 0.0, 1.0, ..., 86.5, 'Mkt&Fin', 66.28],
       [1.0, 0.0, 0.0, ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       [1.0, 0.0, 0.0, ..., 59.0, 'Mkt&Fin', 69.72],
       [1.0, 0.0, 0.0, ..., 70.0, 'Mkt&HR', 60.23],
       [1.0, 0.0, 0.0, ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [38]:
temp= pd.DataFrame(data=x)

In [39]:
temp

0  1  2  3  4  5  6   ...     13     14     15   16    17       18     19
0    0  0  1  0  1  0  0  ...     67     91     58   No    55   Mkt&HR   58.8
1    0  0  1  0  0  1  0  ...  79.33  78.33  77.48  Yes  86.5  Mkt&Fin  66.28
2    1  0  0  1  0  0  1  ...     65     68     64   No    75  Mkt&Fin   57.8
3    0  0  1  0  0  1  1  ...     56     52     52   No    66   Mkt&HR  59.43
4    1  0  0  0  1  0  1  ...   85.8   73.6   73.3   No  96.8  Mkt&Fin   55.5
..  .. .. .. .. .. .. ..  ...    ...    ...    ...  ...   ...      ...    ...
210  1  0  0  0  1  0  0  ...   80.6     82   77.6   No    91  Mkt&Fin  74.49
211  0  0  1  0  0  1  0  ...     58     60     72   No    74  Mkt&Fin  53.62
212  1  0  0  0  1  0  0  ...     67     67     73  Yes    59  Mkt&Fin  69.72
213  1  0  0  0  1  0  0  ...     74     66     58   No    70   Mkt&HR  60.23
214  1  0  0  0  0  1  0  ...     62     58     53   No    89   Mkt&HR  60.22

[215 rows x 20 columns]

In [40]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [16])], remainder='passthrough')

In [41]:
x = np.array(ct.fit_transform(x))

In [42]:
x

array([[1.0, 0.0, 0.0, ..., 55.0, 'Mkt&HR', 58.8],
       [0.0, 1.0, 0.0, ..., 86.5, 'Mkt&Fin', 66.28],
       [1.0, 0.0, 1.0, ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       [0.0, 1.0, 1.0, ..., 59.0, 'Mkt&Fin', 69.72],
       [1.0, 0.0, 1.0, ..., 70.0, 'Mkt&HR', 60.23],
       [1.0, 0.0, 1.0, ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [43]:
temp= pd.DataFrame(data=x)

In [44]:
temp

0  1  2  3  4  5  6  7   ... 13   14     15     16     17    18       19     20
0    1  0  0  0  1  0  1  0  ...  1    1     67     91     58    55   Mkt&HR   58.8
1    0  1  0  0  1  0  0  1  ...  1    2  79.33  78.33  77.48  86.5  Mkt&Fin  66.28
2    1  0  1  0  0  1  0  0  ...  1    3     65     68     64    75  Mkt&Fin   57.8
3    1  0  0  0  1  0  0  1  ...  1    4     56     52     52    66   Mkt&HR  59.43
4    1  0  1  0  0  0  1  0  ...  1    5   85.8   73.6   73.3  96.8  Mkt&Fin   55.5
..  .. .. .. .. .. .. .. ..  ... ..  ...    ...    ...    ...   ...      ...    ...
210  1  0  1  0  0  0  1  0  ...  1  211   80.6     82   77.6    91  Mkt&Fin  74.49
211  1  0  0  0  1  0  0  1  ...  1  212     58     60     72    74  Mkt&Fin  53.62
212  0  1  1  0  0  0  1  0  ...  1  213     67     67     73    59  Mkt&Fin  69.72
213  1  0  1  0  0  0  1  0  ...  0  214     74     66     58    70   Mkt&HR  60.23
214  1  0  1  0  0  0  0  1  ...  1  215     62     58     53    89   Mkt&HR  60.22

[215 rows x 21 columns]

In [45]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [19])], remainder='passthrough')

In [46]:
x = np.array(ct.fit_transform(x))

In [47]:
x

array([[0.0, 1.0, 1.0, ..., 58.0, 55.0, 58.8],
       [1.0, 0.0, 0.0, ..., 77.48, 86.5, 66.28],
       [1.0, 0.0, 1.0, ..., 64.0, 75.0, 57.8],
       ...,
       [1.0, 0.0, 0.0, ..., 73.0, 59.0, 69.72],
       [0.0, 1.0, 1.0, ..., 58.0, 70.0, 60.23],
       [0.0, 1.0, 1.0, ..., 53.0, 89.0, 60.22]], dtype=object)

In [48]:
temp= pd.DataFrame(data=x)

In [49]:
temp

0  1  2  3  4  5  6  7  8   ... 13 14 15   16     17     18     19    20     21
0    0  1  1  0  0  0  1  0  1  ...  1  0  1    1     67     91     58    55   58.8
1    1  0  0  1  0  0  1  0  0  ...  0  0  1    2  79.33  78.33  77.48  86.5  66.28
2    1  0  1  0  1  0  0  1  0  ...  0  0  1    3     65     68     64    75   57.8
3    0  1  1  0  0  0  1  0  0  ...  0  0  1    4     56     52     52    66  59.43
4    1  0  1  0  1  0  0  0  1  ...  0  0  1    5   85.8   73.6   73.3  96.8   55.5
..  .. .. .. .. .. .. .. .. ..  ... .. .. ..  ...    ...    ...    ...   ...    ...
210  1  0  1  0  1  0  0  0  1  ...  1  0  1  211   80.6     82   77.6    91  74.49
211  1  0  1  0  0  0  1  0  0  ...  1  0  1  212     58     60     72    74  53.62
212  1  0  0  1  1  0  0  0  1  ...  1  0  1  213     67     67     73    59  69.72
213  0  1  1  0  1  0  0  0  1  ...  1  1  0  214     74     66     58    70  60.23
214  0  1  1  0  1  0  0  0  0  ...  0  0  1  215     62     58     53    89  60.22

[215 rows x 22 columns]

##train and test sets

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [52]:
print(len(x_train))

182


In [53]:
print(len(x_test))

33


In [54]:
print(len(y_train))

182


In [55]:
print(len(y_test))

33


##Label Encoder 

In [56]:
from sklearn.preprocessing import LabelEncoder 

In [57]:
le = LabelEncoder()

In [58]:
ltrain  = le.fit_transform(y_train)

In [59]:
ltrain

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1])

In [60]:
y_train

array(['Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Not Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       '

In [61]:
ltest = le.fit_transform(y_test)

In [62]:
ltest

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0])

In [63]:
y_test

array(['Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Not Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed'], dtype=object)

##standardization

In [64]:
from sklearn.preprocessing import StandardScaler

In [65]:
sc = StandardScaler()

In [66]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

##train on different algorithms


In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [68]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel = 'linear')
ks_cla = SVC(kernel = 'rbf')

In [69]:
l_cla.fit(x_train, ltrain)
k_cla.fit(x_train, ltrain)
d_cla.fit(x_train, ltrain)
r_cla.fit(x_train, ltrain)
s_cla.fit(x_train, ltrain)
ks_cla.fit(x_train, ltrain)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [70]:
l_pred = l_cla.predict(x_test)
k_pred = k_cla.predict(x_test)
d_pred = d_cla.predict(x_test)
r_pred = r_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test) 

In [71]:
from sklearn.metrics import confusion_matrix

In [72]:
l_c = confusion_matrix(ltest, l_pred)
k_c = confusion_matrix(ltest, k_pred)
d_c = confusion_matrix(ltest, d_pred)
r_c = confusion_matrix(ltest, r_pred)
s_c = confusion_matrix(ltest, s_pred)
ks_c = confusion_matrix(ltest, ks_pred)

##result

In [73]:
from sklearn.metrics import accuracy_score

In [74]:
l_a = accuracy_score(ltest, l_pred)
k_a = accuracy_score(ltest, k_pred)
d_a = accuracy_score(ltest, d_pred)
r_a = accuracy_score(ltest, r_pred)
s_a = accuracy_score(ltest, s_pred)
ks_a = accuracy_score(ltest, ks_pred)

In [77]:
print('Logistic Regression: ' + str(l_a) + '\nKNeighbors: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(ks_a))

Logistic Regression: 0.9090909090909091
KNeighbors: 0.696969696969697
Decision Tree: 0.9090909090909091
Random Forest: 0.9090909090909091
Linear SVC: 0.9090909090909091
Kernel SVC: 0.8484848484848485
